config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
    get '/user', to: 'users#show'
    resources :microposts do
      resources :comments, shallow: true
    end
  end

  unauthenticated do
    root to: 'static_pages#home'
  end

  devise_scope :user do
    get '/sign_in', to: 'devise/sessions#new'
    get '/sign_up', to: 'devise/registrations#new'
    get '/reset_password', to: 'devise/passwords#new'
    get 'users/:id', to: 'users#show', as: :users
    get '/user', to: 'devise/sessions#new'
    get '/user/edit', to: 'devise/sessions#new'
    resources :users
  end

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  match '*unmatched', to: 'application#route_not_found', via: :all

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def about; end

  def contact; end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About TwitterLikeApp</h1>

<p>
  Twitter like app
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

<p>
  You can find me at Github or at LinkedIn
</p>

app/views/static_pages/home.html.erb
<h1>TwitterLikeApp</h1>

<div class="h-75 d-block">
  <p>
    Welcome to home page of Twitter like app!
  </p>
</div>

<div class="h-75 d-block">
  <p>
    <%= link_to "Sign up", sign_up_path, class: "btn btn-lg btn-primary" %>
  </p>
</div>