config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
    get '/user', to: 'users#show'
    resources :microposts do
      resources :comments, shallow: true
    end
  end

  unauthenticated do
    root to: 'static_pages#home'
  end

  devise_scope :user do
    get '/sign_in', to: 'devise/sessions#new'
    get '/sign_up', to: 'devise/registrations#new'
    get '/reset_password', to: 'devise/passwords#new'
    get 'users/:id', to: 'users#show', as: :users
    get '/user', to: 'devise/sessions#new'
    get '/user/edit', to: 'devise/sessions#new'
    resources :users
  end

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  match '*unmatched', to: 'application#route_not_found', via: :all

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost

  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :micropost_id, presence: true
  validates :content, presence: true, length: { maximum: 150 }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :logged_in_user
  before_action :comment_creator_right, only: :destroy
  before_action :find_comment, only: :destroy

  def index; end

  def show; end

  def create
    @micropost = Micropost.find(params[:micropost_id])
    @comment = @micropost.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = 'Comment successfully created'
    else
      flash[:alert] = 'Comment can not be created'
    end
    redirect_to users_path(@micropost.user_id)
  end

  def edit; end

  def update; end

  def destroy
    @comment.destroy
    flash[:notice] = 'Comment deleted'
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:id, :content, :micropost_id, :user_id)
  end

  def logged_in_user
    if current_user.present?
      @comment = Micropost.find_by(id: params[:micropost_id])
    else
      flash[:alert] = 'You need to sign in for viewing, creating or changing ingestions'
      redirect_to sign_in_path
    end
  end

  def find_comment
    if Comment.exists?(params[:id])
      @comment = @micropost.comments.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def comment_creator
    return unless current_user.present? && @comment.present?

    current_user.id == @comment.user_id
  end

  def comment_creator_right
    return if comment_creator

    flash[:alert] = 'You need to be a creator for destroying comments'
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/shared/_comment_form.html.erb
  <%= form_with scope: :comment, url: micropost_comments_path(micropost.id), remote: true do |f| %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Write your comment..." %>
    </div>
    <%= f.submit "Comment"%>
  <% end %>

app/views/comments/shared/_feed.html.erb
<ol>
  <% micropost.comments.each do |comment| %>
    <li>
      <span> Comment # <%= comment.id %> by </span>
      <span ><%= link_to comment.user.email %></span> <br>
      <span ><%= comment.content %></span> <br>
      <span >
        Comment left at <%= comment.created_at.getlocal.strftime("%H:%M %d.%m.%y") %>.
      </span> <br>
      <span><%= link_to "Delete", comment, method: :delete,
                                           action: :destroy,
                                           data: { confirm: "Are you sure?" } %></span>
    </li>
  <% end %>
</ol>