config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
    get '/user', to: 'users#show'
    resources :microposts do
      resources :comments, shallow: true
    end
  end

  unauthenticated do
    root to: 'static_pages#home'
  end

  devise_scope :user do
    get '/sign_in', to: 'devise/sessions#new'
    get '/sign_up', to: 'devise/registrations#new'
    get '/reset_password', to: 'devise/passwords#new'
    get 'users/:id', to: 'users#show', as: :users
    get '/user', to: 'devise/sessions#new'
    get '/user/edit', to: 'devise/sessions#new'
    resources :users
  end

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  match '*unmatched', to: 'application#route_not_found', via: :all

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
# frozen_string_literal: true

class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 150 }
end

app/controllers/microposts_controller.rb
# frozen_string_literal: true

class MicropostsController < ApplicationController
  before_action :logged_in_user
  before_action :micropost_creator_right, only: :destroy
  before_action :find_micropost, only: :destroy

  def index; end

  def show; end

  def new; end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:notice] = 'Micropost successfully created'
    else
      flash[:alert] = 'Micropost can not be created'
    end
    redirect_to root_path
  end

  def edit; end

  def update; end

  def destroy
    @micropost.destroy
    flash[:notice] = 'Post deleted'
    redirect_back(fallback_location: root_path)
  end

  private

  def micropost_params
    params.require(:micropost).permit(:id, :content, :user_id, :created_at, :updated_at)
  end

  def logged_in_user
    if current_user.present?
      @micropost = current_user.microposts.find_by(id: params[:id])
    else
      flash[:alert] = 'You need to sign in for viewing, creating or changing ingestions'
      redirect_to sign_in_path
    end
  end

  def find_micropost
    if Micropost.exists?(params[:id])
      @micropost = Micropost.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def micropost_creator
    return unless current_user.present? && @micropost.present?

    current_user.id == @micropost.user_id
  end

  def micropost_creator_right
    return if micropost_creator

    flash[:alert] = 'You need to be a creator for destroying microposts'
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/microposts_helper.rb
# frozen_string_literal: true

module MicropostsHelper
end

app/views/microposts/shared/_feed.html.erb
<% if @microposts.present? %>
  <ol>
  <% @microposts.each do |micropost| %>
    <li>
      <span> Post # <%= micropost.id %> by </span>
      <span ><%= link_to micropost.user.email %></span> <br>
      <span ><%= micropost.content %></span> <br>
      <span >
        Posted at <%= micropost.created_at.getlocal.strftime("%H:%M %d.%m.%y") %>.
      </span> <br>
      <span><%= link_to "Delete", micropost, method: :delete,
                                           action: :destroy,
                                           data: { confirm: "Are you sure?" } %></span>
      <% if micropost.comments.present? %>
        <section>
          <%= render 'comments/shared/feed', micropost: micropost %>
        </section>
      <% end %>
      <section>
        <%= render 'comments/shared/comment_form', micropost: micropost %>
      </section>
    </li>
  <% end %>
  </ol>
<% else %>
    <span>
      You haven't created any micropost yet!
    </span>
<% end %>

app/views/microposts/shared/_micropost_form.html.erb
  <%= form_with scope: :micropost, url: microposts_path, local: true do |f| %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post"%>
  <% end %>